# Jakobi 11

In [1]:
# from classes import *

# Line_13 = Line(bus_p="1", bus_q="3", impedance=complex(0.08, 0.24), half_line_charging_admittance=complex(0.0, 0.025))
# Line_12 = Line(bus_p="1", bus_q="2", impedance=complex(0.02, 0.06), half_line_charging_admittance=complex(0.0, 0.03))

# display(Line_13.build_Line_pq())
# display(Line_12.build_Line_pq())

# bus1 = Bus(bus_id=1, voltage_magnitude=20, voltage_angle=0)
# bus2 = Bus(bus_id=2, voltage_magnitude=30, voltage_angle=5)
# print(bus1)
# print(bus2)

In [2]:
# Hente fra excel
# Lager liste over linjer
# Lager liste over spenninger med vinkler


# list_power_syst_data = [{'V1': 1, 'delta1': 5, 'P1': 32, 'Q1': 1},
#                        {'V2': 1.05, 'delta2': 2, 'P2': 28, 'Q2': 1},
#                        {'V3': 1.06, 'delta3': 3, 'P3': 15, 'Q3': 2},
#                        {'V4': 1.07, 'delta4': 4, 'P4': 17, 'Q4': 3},
#                        {'V5': 1.08, 'delta5': 5, 'P5': 19, 'Q5': 4}]

# list_line_data = [
#     {'Z12': 0.02 + 0.06j},
#     {'Z13': 0.08 + 0.24j},
#     {'Z23': 0.06 + 0.18j},
#     {'Z24': 0.06 + 0.18j},
#     {'Z25': 0.04 + 0.12j},
#     {'Z34': 0.01 + 0.03j},
#     {'Z45': 0.08 + 0.24j}
#]

# from main.pynb import *

# display(bus_data)
# display(line_data)


from classes import *
import pandas as pd
import os

pathToFile = os.path.abspath(os.curdir)
df_line_data = pd.read_excel(f"{pathToFile}\\files\\network_configuration.xlsx", sheet_name="Line_data")
df_bus_data = pd.read_excel(f"{pathToFile}\\files\\network_configuration.xlsx", sheet_name="Bus_data")
# display(df_line_data)
# display(bus_data)
line_data = df_line_data.to_dict(orient='records')
bus_data = df_bus_data.to_dict(orient='records')
# display(df_bus_data)
line_admittences = []
display(line_data)

for line_dict in line_data:
    line = Line(
        bus_p=line_dict['From line'],
        bus_q=line_dict['To line'],
        impedance=complex(line_dict['R[pu]'], line_dict['X[pu]']),
        half_line_charging_admittance=complex(line_dict['Half Line Charging Admittance'])
    )
    line_admittences.append(line.build_Line_Y_bus())


# display(line_admittences)
#display(Line_13.build_Line_pq())

bus1 = Bus(bus_id=1, voltage_magnitude=20, voltage_angle=0)
#print(bus1)



test_YBUS = pd.DataFrame(0, index=range(1, 6), columns=range(1,6))
test_YBUS[1] = [complex(25/4,-3739/200), complex(-5, 15), complex(-5/4, 15/4), 0, 0]
test_YBUS[2] = [complex(-5, 15), complex(65/6, -6483/200), complex(-5/3, 5), complex(-5/3, 5), complex(-5/2, 15/2)]
test_YBUS[3] = [complex(-5/4, 15/4), complex(-5/3, 5), complex(155/12, -7739/200), complex(-10, 30), 0]
test_YBUS[4] = [0, complex(-5/3, 5), complex(-10, 30), complex(155/12, -7739/200), complex(-5/4, 15/4)]
test_YBUS[5] = [0, complex(-5/2, 15/2), 0, complex(-5/4, 15/4), complex(15/4, -1121/100)]

value = test_YBUS.at[1, 2].imag


display(value)





[{'From line': 1,
  'To line': 2,
  'R[pu]': 0.02,
  'X[pu]': 0.06,
  'Half Line Charging Admittance': 0.03,
  'Real Power Line Limit': 0.8},
 {'From line': 1,
  'To line': 3,
  'R[pu]': 0.08,
  'X[pu]': 0.24,
  'Half Line Charging Admittance': 0.025,
  'Real Power Line Limit': 0.3},
 {'From line': 2,
  'To line': 3,
  'R[pu]': 0.06,
  'X[pu]': 0.18,
  'Half Line Charging Admittance': 0.02,
  'Real Power Line Limit': 0.2},
 {'From line': 2,
  'To line': 4,
  'R[pu]': 0.06,
  'X[pu]': 0.18,
  'Half Line Charging Admittance': 0.02,
  'Real Power Line Limit': 0.2},
 {'From line': 2,
  'To line': 5,
  'R[pu]': 0.04,
  'X[pu]': 0.12,
  'Half Line Charging Admittance': 0.015,
  'Real Power Line Limit': 0.6},
 {'From line': 3,
  'To line': 4,
  'R[pu]': 0.01,
  'X[pu]': 0.03,
  'Half Line Charging Admittance': 0.01,
  'Real Power Line Limit': 0.1},
 {'From line': 4,
  'To line': 5,
  'R[pu]': 0.08,
  'X[pu]': 0.24,
  'Half Line Charging Admittance': 0.025,
  'Real Power Line Limit': 0.1}]

TypeError: __init__() missing 4 required positional arguments: 'gen_MW', 'gen_MVAr', 'load_MW', and 'load_MVAr'

In [ ]:
import math

list_dict_power = [{'P1': False, 'P2': True, 'P3': True, 'P4': True, 'P5': True},
                  {'Q1': False, 'Q2': False, 'Q3': True, 'Q4': True, 'Q5': True}]


def J11_calc(bus_data, line_data, list_dict_power):

    true_count = 0
    for power_dict in list_dict_power:
        for key, value in power_dict.items():
            if value is True:
                true_count += 1
        # Teller "true_count" for å vite størrelsen på J11

            J11 = np.zeros((true_count, true_count))

            # Iterate through each row and column of the J11 array
            for row in range(true_count):
                for col in range(true_count):
                    if row == col:
                        continue
                    # Set the element value
                    J11[row, col] = bus_data[row-1]['Assumed bus voltage (pu)'] * bus_data[col-1]['Assumed bus voltage pu()'] * (test_YBUS.at[row, col].real * math.sin(bus_data[col-1]['Assumed bus voltage pu()']   -Vj_ang) - y_line_ij.imag * math.cos(Vi_ang-Vj_ang))

# FÅ INN KOMPLEKS VOLTAGE I LINJEN OVER

            
test = J11_calc(bus_data=bus_data,
         line_data=line_data,
         list_dict_power=list_dict_power)









    # dPi_dDj = Vi_mag * Vj_mag * (y_line_ij.real * math.sin(Vi_ang-Vj_ang) - y_line_ij.imag * math.cos(Vi_ang-Vj_ang))


    # if (bus_i == bus_j):     # Diagonal
    #     # Lager variabler inni funksjonen
  
    # else:                   # Off-diagonal
    #     Vi_mag = bus_i.voltage_magnitude
    #     Vi_ang = bus_i.voltage_angle
    #     Vj_mag = bus_j.voltage_magnitude
    #     Vj_ang = bus_j.voltage_angle

    #     y_line_ij = 1/line_ij.impedance

    #     dPi_dDj = Vi_mag * Vj_mag * (y_line_ij.real * math.sin(Vi_ang-Vj_ang) - y_line_ij.imag * math.cos(Vi_ang-Vj_ang))
    #     return dPi_dDj



    # # Loop through all pairs of nodes
    # for node_from in range(1, true_count + 1):
    #     for node_to in range(1, true_count + 1):
    #         if node_from == node_to:
    #             continue  # Skip self-connections

    #         connection_found = False

    #         for line_dict in line_data:
    #             if (line_dict['From line'] == node_from and line_dict['To line'] == node_to):
                   

    #                 connection_found = True
    #                 r_value = line_dict['R[pu]']
    #                 x_value = line_dict['X[pu]']
    #                 # Perform your action with r_value and x_value
    #                 print(f"Connection between {node_from} and {node_to}")
    #                 # Exit the loop since you found a connection
    #                 break

    #         if not connection_found:
    #             # No connection between node_from and node_to is found
    #             # Continue with other actions if needed
    #             pass

J11_calc(bus_data, line_data, list_dict_power)

Connection between 1 and 2
Connection between 1 and 3
Connection between 2 and 3
Connection between 2 and 4
Connection between 2 and 5
Connection between 3 and 4
Connection between 4 and 5


In [ ]:
# bus_num = 5

# def J11_calc(bus_data, line_data, bus_num):

#     J11 = np.zeros((bus_num, bus_num))

#     # Loop through all pairs of nodes
#     for node_from in range(1, bus_num + 1):
#         for node_to in range(1, bus_num + 1):
#             if node_from == node_to:
#                 continue  # Skip self-connections

#             connection_found = False

#             for line_dict in line_data:
#                 if (line_dict['From line'] == node_from and line_dict['To line'] == node_to):
                   

#                     connection_found = True
#                     r_value = line_dict['R[pu]']
#                     x_value = line_dict['X[pu]']
#                     # Perform your action with r_value and x_value
#                     print(f"Connection between {node_from} and {node_to}")
#                     # Exit the loop since you found a connection
#                     break

#             if not connection_found:
#                 # No connection between node_from and node_to is found
#                 # Continue with other actions if needed
#                 pass

# J11_calc(bus_data, line_data, bus_num)

In [ ]:








    dPi_dDj = Vi_mag * Vj_mag * (y_line_ij.real * math.sin(Vi_ang-Vj_ang) - y_line_ij.imag * math.cos(Vi_ang-Vj_ang))


    from_line = 1
    to_line = 3

    desired_R_value = None      # Zero value kun for å initialisere

    for line_dict in line_data:
        if line_dict['From line'] == from_line and line_dict['To line'] == to_line:
            desired_R_value = line_dict['R[pu]']
            break

    if desired_R_value is not None:
        print(f"The 'R[pu]' value for Line 1 to 3 is: {desired_R_value}")
    else:
        print("Line not found in line_data.")


    return J11

print(J11_calc(bus_data, line_data, P_known))


The 'R[pu]' value for Line 1 to 3 is: 0.08
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
import math




def J11_calc(buses: List[classes.Bus], lines: List[classes.Line]):





   for dictionary in line_data:
        for key, value in dictionary.items():
            if key.startswith('Z12'):
                print(value)





        Vi_mag = bus_i.voltage_magnitude
        Vi_ang = bus_i.voltage_angle
        Vj_mag = bus_j.voltage_magnitude
        Vj_ang = bus_j.voltage_angle



    if (bus_i == bus_j):     # Diagonal
        # Lager variabler inni funksjonen
  
    else:                   # Off-diagonal
        Vi_mag = bus_i.voltage_magnitude
        Vi_ang = bus_i.voltage_angle
        Vj_mag = bus_j.voltage_magnitude
        Vj_ang = bus_j.voltage_angle

        y_line_ij = 1/line_ij.impedance

        dPi_dDj = Vi_mag * Vj_mag * (y_line_ij.real * math.sin(Vi_ang-Vj_ang) - y_line_ij.imag * math.cos(Vi_ang-Vj_ang))
        return dPi_dDj



In [ ]:


def J11_off_diag_calc(bus_i, bus_j, line_ij):    # MIXED FORM: Voltage in polar, impedance in cartesian
    
    if (bus_i == bus_j):     # Diagonal
        # Lager variabler inni funksjonen
        Vi_mag = bus_i.voltage_magnitude
        Vi_ang = bus_i.voltage_angle
        Vj_mag = bus_j.voltage_magnitude
        Vj_ang = bus_j.voltage_angle

        y_line_ij = 1/line_ij.impedance

        dPi_dDj = Vi_mag * Vj_mag * (y_line_ij.real * math.sin(Vi_ang-Vj_ang) - y_line_ij.imag * math.cos(Vi_ang-Vj_ang))
        return dPi_dDj
    else:                   # Off-diagonal


# Bruker grader! Dobbelsjekk at det er rett.
# Plasser i tabell/ liste/ dataframe?
J11_off_diag_calc(bus1, bus2, Line_12)


######################################################################################


# Sett inn liste med spenning og vinkel på alle busser
# Sett inn liste med impedanser på alle linjer

def J11_diag_calc(buses: List[classes.Bus], lines: List[classes.Line]):    # MIXED FORM: Voltage in polar, impedance in cartesian







    num_busses = size.buses

    List[classes.Bus], buses

    # Bruker grader! Sjekk at det er rett.
        for i in range(1, num_busses + 1):
            if i == int(bus_i.bus_id):
                continue
            else:
                dPi_dDi = 2 #Må få laget en liste over spenninger og vinkler i alle busser før formel kan legges inn her.


        return dPi_dDi

    # Plasser i tabell/ liste/ dataframe?
    J11_diag_calc(bus1, bus2, Line_12)

IndentationError: expected an indented block (2590140238.py, line 19)